---
- name: Create directory for Postgres
  ansible.builtin.file:
    state: directory
    path: /mnt/data/postgres
    mode: 0770

- name: Fetch password secret
  ansible.builtin.command: gcloud secrets versions access latest --secret "{{ hostvars[inventory_hostname]['instance_name'] }}-postgres-password"
  register: db_password

- name: Fetch user secret
  ansible.builtin.command: gcloud secrets versions access latest --secret "{{ hostvars[inventory_hostname]['instance_name'] }}-postgres-user"
  register: db_user

- name: Start Postgres container
  ansible.builtin.docker_container:
    name: postgres
    image: "postgres:17.0"
    state: started
    volumes:
      - "/mnt/data/postgres:/etc/pgdata"
    networks:
      - name: "datomic-network"
    env:
      POSTGRES_PASSWORD: "{{ db_password.stdout }}"
      POSTGRES_USER: "{{ db_user.stdout }}"
      POSTGRES_DB: datomic
      PGDATA: /etc/pgdata
    ports:
      - "5432:5432"
    restart_policy: unless-stopped
